# Generated by Django 5.0.2 on 2024-12-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Schoolclass',
        ),
    ]
