# Generated by Django 5.0.2 on 2024-12-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Reason_absent',
            new_name='reason_absent',
        ),
    ]
