# Generated by Django 5.0.2 on 2024-12-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_alter_customuser_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
